/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"
#include "juce_StandaloneFilterWindow.h"


//==============================================================================
class TestStandaloneApplication  : public JUCEApplication
{
public:
    //==============================================================================
    TestStandaloneApplication() {}

    const String getApplicationName()       { return ProjectInfo::projectName; }
    const String getApplicationVersion()    { return ProjectInfo::versionString; }
    bool moreThanOneInstanceAllowed()       { return true; }

    //==============================================================================
    void initialise (const String& commandLine)
    {
        standaloneFilterWindow = new StandaloneFilterWindow(JUCEApplication::getInstance()->getApplicationName(), Colours::lightgrey, nullptr);
        standaloneFilterWindow->setTitleBarButtonsRequired (DocumentWindow::allButtons, false);
        standaloneFilterWindow->setVisible (true);
        standaloneFilterWindow->setResizable (true, true);
    }

    void shutdown()
    {
        standaloneFilterWindow = nullptr; // (deletes our window)
    }

    //==============================================================================
    void systemRequestedQuit()
    {
        // This is called when the app is being asked to quit: you can ignore this
        // request and let the app carry on running, or call quit() to allow the app to close.
        quit();
    }

    void anotherInstanceStarted (const String& commandLine)
    {
        // When another instance of the app is launched while this one is running,
        // this method is invoked, and the commandLine parameter tells you what
        // the other instance's command-line arguments were.
    }
    
private:
    ScopedPointer<StandaloneFilterWindow> standaloneFilterWindow;
};

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (TestStandaloneApplication)
